# Practice!

![](https://media.giphy.com/media/11RzDlgr9U8wM0/giphy.gif)

In [1]:
# import pandas and plotly express libraries
import pandas as pd
import plotly.express as px

### Effort 1 - Inspect your data!

In this practice assignment, you will work with a dataset of the top 1,000 streamers on the Twitch platform.

Load `twitch.csv` into a pandas DataFrame and preview the first five rows. Recall that the `twitch.csv` is in the `datasets` folder.

In [2]:
# Load the dataset into pandas and preview it
df = pd.read_csv('datasets/twitch.csv')

Preview the last seven rows of the DataFrame

In [3]:
# preview last 7 rows of data
df.tail(7)

,Channel,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
993,LAGTVMaximusBlack,123125340,161535,7138,725,256353,13251,2310313,True,True,English
994,Destructoid,122628630,103020,14566,1190,48007,8995,87603521,True,False,English
995,LITkillah,122524635,13560,21359,9104,601927,562691,2162107,True,False,Spanish
996,빅헤드 (bighead033),122523705,153000,3940,793,213212,52289,4399897,True,False,Korean
997,마스카 (newmasca),122452320,217410,6431,567,109068,-4942,3417970,True,False,Korean
998,AndyMilonakis,122311065,104745,10543,1153,547446,109111,3926918,True,False,English
999,Remx,122192850,99180,13788,1205,178553,59432,2049420,True,False,French

View twenty randomly chosen rows of the DataFrame

In [4]:
# sample 20 random rows
df.sample(20)

,Channel,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained,Partnered,Mature,Language
890,Japan_ASMR,138935670,509670,496,271,67707,32649,1272641,True,False,Japanese
518,Mibrtv,228640020,82620,151094,3310,250709,242229,6671227,True,False,Portuguese
889,JonBams,139067415,88830,5577,1522,309837,75728,1940922,True,True,English
33,DrLupo,1517612010,172350,90696,8311,4115083,567795,47295386,True,False,English
322,오킹 (obm1025),346276365,96000,19328,3563,428179,244442,8920133,True,False,Korean
638,SovietWomble,187497450,63360,9616,2900,1368076,214775,5846971,True,True,English
839,Tourva,146412075,116070,5067,1185,287553,182413,7888629,True,True,English
924,CouRageJD,131341275,14010,72100,8717,2115596,120434,2874860,False,False,English
932,StarCraft,130159470,14850,56109,6636,342409,22130,4110003,True,False,English
507,룩삼 (looksam),232224165,75030,32222,3302,285474,14351,7901792,True,False,Korean
994,Destructoid,122628630,103020,14566,1190,48007,8995,87603521,True,False,English
324,BlackUFA,345166455,88035,10349,3889,279922,34803,12888906,True,False,Russian
842,PainLivestream,145610160,89775,15002,1635,435872,81619,2283772,True,True,German
415,BeyondTheSummit_PT,282753480,339000,49496,807,203549,60955,9694977,True,False,Portuguese
147,coscu,622424175,77160,80444,8919,1865296,1061265,19438119,True,False,Spanish
210,JoshOG,510984165,159300,85051,2957,1748928,120782,20688501,True,False,English
801,CaMaK,154277370,87375,9437,1759,151886,7578,3019137,True,True,French
444,Warframe,262160025,13740,346131,12843,1254031,282680,5405191,True,False,English
562,JonVlogs,212114490,81180,21617,2239,480299,261559,3260166,True,False,Portuguese
946,HunterGodBr,128369655,89520,51612,1737,258876,254260,14078099,True,False,Portuguese

View the index of the DataFrame

In [5]:
# View the index
df.index

RangeIndex(start=0, stop=1000, step=1)

View the column names

In [6]:
# View the column names
df.columns

Index(['Channel', 'Watch time(Minutes)', 'Stream time(minutes)',
       'Peak viewers', 'Average viewers', 'Followers', 'Followers gained',
       'Views gained', 'Partnered', 'Mature', 'Language'],
      dtype='object')

### Effort 2 - Gather facts about your data!

View information about the DataFrame, including its index, number of rows without missing data, and data type of each column

In [8]:
# View basic information about the DataFrame, including data types,
# index, column names, and number of rows without missing data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Channel               1000 non-null   object
 1   Watch time(Minutes)   1000 non-null   int64
 2   Stream time(minutes)  1000 non-null   int64
 3   Peak viewers          1000 non-null   int64
 4   Average viewers       1000 non-null   int64
 5   Followers             1000 non-null   int64
 6   Followers gained      1000 non-null   int64
 7   Views gained          1000 non-null   int64
 8   Partnered             1000 non-null   bool
 9   Mature                1000 non-null   bool
 10  Language              1000 non-null   object
dtypes: bool(2), int64(7), object(2)
memory usage: 72.4+ KB

View the statistical summaries of each numerical column, including the mean, median (50th percentile), min and max values, and the standard deviation. Use the `.describe()` method.

In [9]:
# View statistical summaries by column
df.describe()

,Watch time(Minutes),Stream time(minutes),Peak viewers,Average viewers,Followers,Followers gained,Views gained
count,1.000000e+03,1000.000000,1000.000000,1000.000000,1.000000e+03,1.000000e+03,1.000000e+03
mean,4.184279e+08,120515.160000,37065.051000,4781.040000,5.700541e+05,2.055185e+05,1.166817e+07
std,5.496355e+08,85376.201364,60314.307686,8453.684965,8.044134e+05,3.399137e+05,2.490572e+07
min,1.221928e+08,3465.000000,496.000000,235.000000,3.660000e+03,-1.577200e+04,1.757880e+05
25%,1.631899e+08,73758.750000,9113.750000,1457.750000,1.705462e+05,4.375825e+04,3.880602e+06
50%,2.349908e+08,108240.000000,16676.000000,2425.000000,3.180630e+05,9.835200e+04,6.456324e+06
75%,4.337399e+08,141843.750000,37569.750000,4786.250000,6.243322e+05,2.361308e+05,1.219676e+07
max,6.196162e+09,521445.000000,639375.000000,147643.000000,8.938903e+06,3.966525e+06,6.701375e+08

### Effort 3 - Visualize your data!

Use `px.histogram()` to create a bar chart of the average number of followers by streaming language. Use `histfunc='avg'` to aggregate the data. Which languages have the highest number of followers on average?

In [ ]:
# Bar chart of the average number of followers by streaming language
px.histogram(df, x='Language', y='')

## Level Up

Create a scatter plot of the number of followers and the total stream time. Total stream time should be on the x-axis, and the number of followers should be on the y-axis. Does higher stream time correlate with an increase in the number of followers?

In [ ]:
# Scatter plot of number of followers and total stream time.